"""Convert downloaded English WebVTT captions to indexed study transcripts."""
import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / 'captions'
RAW = OUT / 'raw'


def cues(path):
    previous = []
    previous_end = -1
    source = path.read_text().strip()
    rolling = '<c>' in source or 'align:start position:0%' in source
    for block in re.split(r'\n\s*\n', source):
        lines = block.splitlines()
        timing = next((i for i, line in enumerate(lines) if ' --> ' in line), None)
        if timing is None:
            continue
        start, end = lines[timing].split(' --> ')
        def seconds(value):
            h, m, s = value.split()[0].split(':')
            return int(h) * 3600 + int(m) * 60 + float(s)
        text = html.unescape(re.sub(r'<[^>]*>', '', ' '.join(lines[timing + 1:])))
        words = text.split()
        if not words:
            continue
        original = words[:]
        # Rolling automatic captions repeat text in overlapping adjacent cues.
        if rolling and seconds(start) <= previous_end + 0.05:
            for n in range(min(len(previous), len(words)), 0, -1):
                if previous[-n:] == words[:n]:
                    words = words[n:]
                    break
        previous, previous_end = original, seconds(end)
        if words:
            yield seconds(start), ' '.join(words)


def stamp(seconds):
    seconds = int(seconds)
    return f'{seconds // 3600:02d}:{seconds // 60 % 60:02d}:{seconds % 60:02d}'


def main():
    playlist = json.loads((ROOT / 'playlist.json').read_text())
    entries = playlist['entries'][:34]
    assert len(entries) == 34
    rows, results = [], []
    for position, entry in enumerate(entries, 1):
        video_id, title = entry['id'], entry['title']
        base = f'{position:02d}_{video_id}'
        info_path = RAW / f'{base}.info.json'
        info = json.loads(info_path.read_text()) if info_path.exists() else {}
        choices = [('en', 'Uploaded English captions')]
        if 'en' not in info.get('subtitles', {}):
            choices = [('en-orig', 'Autogenerated English captions'), ('en', 'Autogenerated English captions')]
        choices = [('en-6UJrWS5jR_I', 'English — NPTEL Verified'), ('en-LUU0EuDKgKo', 'English — NPTEL Official')] + choices
        selected = next(((RAW / f'{base}.{lang}.vtt', kind) for lang, kind in choices if (RAW / f'{base}.{lang}.vtt').exists()), None)
        slug = re.sub(r'[^\w-]+', '_', title).strip('_')
        filename = f'{position:02d}_{slug}.md'
        url = f'https://www.youtube.com/watch?v={video_id}'
        if not selected:
            rows.append(f'| {position:02d} | {title} | Missing captions |')
            results.append({'position': position, 'id': video_id, 'status': 'missing'})
            continue
        path, kind = selected
        segments = list(cues(path))
        assert segments, f'Empty transcript: {path}'
        paragraphs, group, start = [], [], segments[0][0]
        for time, text in segments:
            if time - start >= 60 and group:
                paragraphs.append(f'### [{stamp(start)}]({url}&t={int(start)}s)\n\n' + ' '.join(group))
                group, start = [], time
            group.append(text)
        if group:
            paragraphs.append(f'### [{stamp(start)}]({url}&t={int(start)}s)\n\n' + ' '.join(group))
        content = f'# {position:02d}. {title}\n\n- Playlist position: {position} of 60 (selected range: 1–34)\n- Video: [{title}]({url})\n- Caption source: {kind}\n- Raw captions: [{path.name}](raw/{path.name})\n\n## Transcript\n\n' + '\n\n'.join(paragraphs) + '\n'
        (OUT / filename).write_text(content)
        words = sum(len(text.split()) for _, text in segments)
        rows.append(f'| {position:02d} | [{title}]({filename}) | {kind} |')
        results.append({'position': position, 'id': video_id, 'status': 'complete', 'file': filename, 'words': words, 'last_caption_seconds': segments[-1][0], 'duration_seconds': info.get('duration')})
    index = '# Reinforcement Learning — lecture transcripts\n\n' + playlist['title'] + '\n\n[YouTube playlist](https://www.youtube.com/playlist?list=PLEAYkSg4uSQ0Hkv_1LHlJtC_wqwVu6RQX)\n\nOnly playlist entries **1–34** are included, in playlist order at extraction.\n\n## Using these files\n\nUpload the desired lecture Markdown files to your study AI. These are caption transcripts, not summaries. Wording is preserved apart from whitespace, subtitle markup, and repeated rolling captions. Timestamp headings occur approximately every minute and link to the video.\n\nCaptions may contain errors in technical terms, equations, or names, including uploaded tracks. Autogenerated tracks are labeled. Visual equations and diagrams are not captured unless spoken in the captions. Raw downloaded tracks and metadata are retained in `raw/`.\n\n## Lectures\n\n| Position | Lecture | Caption source |\n| --- | --- | --- |\n' + '\n'.join(rows) + '\n\n## Regeneration\n\nRun `python3 build_markdown.py` from the project directory to rebuild from the saved raw captions. `manifest.json` records coverage and word counts.\n'
    (OUT / 'README.md').write_text(index)
    (OUT / 'manifest.json').write_text(json.dumps(results, indent=2) + '\n')
    print(json.dumps({'complete': sum(r['status'] == 'complete' for r in results), 'missing': [r['position'] for r in results if r['status'] == 'missing'], 'words': sum(r.get('words', 0) for r in results)}, indent=2))


if __name__ == '__main__':
    main()
